detectable_greetings = ["hello", "hi", "yo", "sup"]
list_of_greetings = ["I hope you have been well?", "How are you?", "Everything going well?", "What's up?", "How's it going?"]
list_of_sorrys = ["Sorry, I don't understand what you mean.", "I'm not sure I quite understood that.", "I don't know what you mean, sorry."]
list_of_goods = ["That's good to hear!", "Nice to hear!", "That's good!"]
list_of_yes = ["What would you like help with?", "Great! Where shall we begin?", "I will do my best to help with whatever I can."]
list_of_no = ["OK, enjoy your day.", "I will be here if you change your mind.", "No problem, enjoy the rest of the day."]
